spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      username: root
      password: bitc5600
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

