spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 105243604114-hj3rjnlk4r6um1tnidhdcdhhk0i0fkup.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      username: root
      password: bitc5600
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: t3reego@gmail.com
    password: 3gogogo!
    properties:
      mail.smtp.auth: true
      mail.stmp.starttls.enable: true